### ISSUE TITLE
KeyError: 'serverTime' while invoking bitbns method

### ISSUE THREAD

**Issue by bigbomaks** [bitbns-official/bitbnspy#9]
Sample Code used 
```
from bitbnspy import bitbns
key = '***********************'
secretKey = '**********************'
bitbnsObj = bitbns(key, secretKey)
print(bitbnsObj.getSellOrderBook('XRPUSDT'))
```

Error - 
```
C:\Users\**********\PycharmProjects\bitbns\venv\Scripts\python.exe C:/Users/singha2/PycharmProjects/bitbns/test.py
Traceback (most recent call last):
  File "C:/Users/*********/PycharmProjects/bitbns/test.py", line 4, in <module>
    bitbnsObj = bitbns(key, secretKey)
  File "C:\Users\********\PycharmProjects\bitbns\venv\lib\site-packages\bitbnspy\bitbnspy.py", line 25, in __init__
    serverTime = int(response['serverTime'])
KeyError: 'serverTime'

Process finished with exit code 1

```

**Comment by tanmesh** [comment]
What is your Python version?

**Comment by bigbomaks** [comment]
Using Python 3.6.0
Its working now 
Thanks

**Comment by tanmesh** [comment]
May I know what the issue you were facing?

**Comment by bigbomaks** [comment]
@tanmesh It is working fine now 
Will report issues if faced any

**Comment by 12345k** [comment]
Code
```
from bitbnspy import bitbns
import os
from dotenv import load_dotenv

key = os.getenv("public_key")
secretKey = os.getenv("secret_key")

bitbnsObj = bitbns(key, secretKey)
print(bitbnsObj.getSellOrderBook('XRPUSDT'))

```
Output
```
(crypto) ➜  btsbns python app.py 
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    bitbnsObj = bitbns(key, secretKey)
  File "/home/******/.virtualenvs/crypto/lib/python3.8/site-packages/bitbnspy/bitbnspy.py", line 25, in __init__
    serverTime = int(response['serverTime'])
KeyError: 'serverTime'
```


I am facing this issue and I am using python 3.8
